commit 6

diff --git a/.github/workflows/generate-ascii.yml b/.github/workflows/generate-ascii.yml
--- a/.github/workflows/generate-ascii.yml
+++ b/.github/workflows/generate-ascii.yml
@@ -3,16 +3,30 @@ name : generate ascii artwork
 on: push
 
 jobs:
-    ascii_job:
+    job1_build:
         runs-on: ubuntu-latest
         steps:
-            - name: checkout repo
-              uses: actions/checkout@v4
-            
-            - name: list files
-              run: ls -ltra
+            - name: install cowsay
+              run: sudo apt-get install cowsay -y
+            - name: execute cowsay cmd
+              run: cowsay -f dragon "run for cover soy dragon" >> dragon.txt
+            - name: sleep for 30 seconds
+              run: sleep 30
+        
+    job2_test:
+        runs-on: ubuntu-latest
+        needs: job1_build
+        steps:
+            - name: sleep for 10 seconds
+              uses: sleep 10
 
-            - name: execute script
+            - name: test file exists
+              run: grep -i "dragon" dragon.txt || echo "File not found"
+
+    job3_deploy:
+        runs-on: ubuntu-latest
+        steps:
+            - name: display file content
               run: |
-               chmod +x ascii-script.sh
-               ./ascii-script.sh
+                cat dragon.txt
+                ls -ltra
